-- Type 21 record table (BLPU)
CREATE TABLE BLPU (
	RECORD_IDENTIFIER NUMBER,
	CHANGE_TYPE VARCHAR2(1),
	PRO_ORDER NUMBER,
	UPRN NUMBER,
	LOGICAL_STATUS NUMBER,
	BLPU_STATE NUMBER,
	BLPU_STATE_DATE DATE,
	PARENT_UPRN NUMBER,
	X_COORDINATE FLOAT,
	Y_COORDINATE FLOAT,
	LATITUDE FLOAT,
	LONGITUDE FLOAT,
	RPC NUMBER,
	LOCAL_CUSTODIAN_CODE NUMBER,
	COUNTRY VARCHAR2(1),
	START_DATE DATE,
	END_DATE DATE,
	LAST_UPDATE_DATE DATE,
	ENTRY_DATE DATE,
	ADDRESSBASE_POSTAL VARCHAR2(1),
	POSTCODE_LOCATOR VARCHAR2(8),
	MULTI_OCC_COUNT NUMBER
);

-- Type 24 record table (LPI)
CREATE TABLE LPI (
	RECORD_IDENTIFIER NUMBER,
	CHANGE_TYPE VARCHAR2(1),
	PRO_ORDER NUMBER,
	UPRN NUMBER,
	LPI_KEY VARCHAR2(14),
	LANGUAGE VARCHAR2(3),
	LOGICAL_STATUS NUMBER,
	START_DATE DATE,
	END_DATE DATE,
	LAST_UPDATE_DATE DATE,
	ENTRY_DATE DATE,
	SAO_START_NUMBER NUMBER,
	SAO_START_SUFFIX VARCHAR2(2),
	SAO_END_NUMBER NUMBER,
	SAO_END_SUFFIX VARCHAR2(2),
	SAO_TEXT VARCHAR2(90),
	PAO_START_NUMBER NUMBER,
	PAO_START_SUFFIX VARCHAR2(2),
	PAO_END_NUMBER NUMBER,
	PAO_END_SUFFIX VARCHAR2(2),
	PAO_TEXT VARCHAR2(90),
	USRN NUMBER,
	USRN_M_INDICATOR VARCHAR2(1),
	AREA_NAME VARCHAR2(35),
	addLEVEL VARCHAR2(30),
	OFFICIAL_FLAG VARCHAR2(1)
);

-- Type 32 record table (classification)
CREATE TABLE CLASSIFICATION (
	RECORD_IDENTIFIER NUMBER,
	CHANGE_TYPE VARCHAR2(1),
	PRO_ORDER NUMBER,
	UPRN NUMBER,
	CLASS_KEY VARCHAR2(14),
	CLASSIFICATION_CODE VARCHAR2(6),
	CLASS_SCHEME VARCHAR2(60),
	SCHEME_VERSION FLOAT,
	START_DATE DATE,
	END_DATE DATE,
	LAST_UPDATE_DATE DATE,
	ENTRY_DATE DATE
);
